import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Title from 'antd/es/typography/Title';
import { motion } from 'framer-motion';
import news1 from '../../images/main_content/news/news1.png';
import news2 from '../../images/main_content/news/news2.png';
import news3 from '../../images/main_content/news/news3.png';
const Main_page_news = () => {
    return (_jsxs("div", Object.assign({ className: "news-section" }, { children: [_jsx(motion.div, Object.assign({ className: "news-title-container", initial: { opacity: 0, y: -20 }, whileInView: { opacity: 1, y: 0 }, transition: { duration: 0.8 }, viewport: { once: false } }, { children: _jsxs(Title, Object.assign({ className: "news-title" }, { children: [_jsx("div", { className: "news-title-line" }), "NEWS", _jsx("div", { className: "news-title-line" })] })) })), _jsxs("div", Object.assign({ className: "news-container" }, { children: [_jsxs(motion.div, Object.assign({ className: "news-item", initial: { opacity: 0, y: 50 }, whileInView: { opacity: 1, y: 0 }, transition: { duration: 0.8 }, viewport: { once: false } }, { children: [_jsx("img", { src: news1, alt: "Main_page_news 1", className: "news-image" }), _jsx("p", Object.assign({ className: "news-text" }, { children: "The issues of parents raising special needs children were discussed at the JSDP platform." }))] })), _jsxs(motion.div, Object.assign({ className: "news-item", initial: { opacity: 0, y: 50 }, whileInView: { opacity: 1, y: 0 }, transition: { duration: 0.8, delay: 0.2 }, viewport: { once: false } }, { children: [_jsx("img", { src: news2, alt: "Main_page_news 2", className: "news-image" }), _jsx("p", Object.assign({ className: "news-text" }, { children: "A special day for special children." }))] })), _jsxs(motion.div, Object.assign({ className: "news-item", initial: { opacity: 0, y: 50 }, whileInView: { opacity: 1, y: 0 }, transition: { duration: 0.8, delay: 0.4 }, viewport: { once: false } }, { children: [_jsx("img", { src: news3, alt: "Main_page_news 3", className: "news-image" }), _jsx("p", Object.assign({ className: "news-text" }, { children: "A sports relay competition was held among special needs children in Nur-Sultan." }))] }))] }))] })));
};
export default Main_page_news;
//# sourceMappingURL=main_page_news.js.map