import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import './styles.scss';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import Main_Header from './main/header/header';
import MainContent from './main/main_content/main';
import News from './main/main_content/news';
import Header_buttons from './main/main_content/header_buttons';
import Footer_Content from './main/main_content/footer';
import Register from './register/register';
import Login from './login/login';
import ForgotPassword from './forget_password/forget_password';
import SymptomTracker from './main_panel/symptom_tracker/symptom_tracker';
import Menu from './menu/menu';
import UserProfile from './main_panel/profile/profile';
import VerifyOTP from './register/sendOTP';
import InformationHub from './main_panel/info_hub/information_hub';
import DiscussionForum from './main_panel/discussion_forum/discussion_forum';
import Discussion_details from './main_panel/discussion_forum/discussion_details';
import NewsDetails from './main_panel/info_hub/news_details';
import SpecialistDetails from './main_panel/info_hub/specialist_details';
import TherapyCenterDetails from './main_panel/info_hub/therapy_centers_details';
import Marketplace from './main_panel/marketplace/marketplace';
import MarketplaceDetails from './main_panel/marketplace/marketplace_details';
import IkomekAssistant from './main_panel/ikomek_ai_assistant/ikomek_assistant';
import PrivacyPolicy from './main/main_content/footer_links/privacy_policy';
import Support from './main/main_content/footer_links/support';
import ContactUs from './main/main_content/footer_links/contact_us';
const App = () => {
    return (_jsx(Router, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsxs(_Fragment, { children: [_jsx(Main_Header, {}), _jsx(MainContent, {}), _jsx(News, {}), _jsx(Header_buttons, {}), _jsx(Footer_Content, {})] }) }), _jsx(Route, { path: "/privacy-policy", element: _jsx(PrivacyPolicy, {}) }), _jsx(Route, { path: "/support", element: _jsx(Support, {}) }), _jsx(Route, { path: "/contact", element: _jsx(ContactUs, {}) }), _jsx(Route, { path: "/register", element: _jsx(Register, {}) }), _jsx(Route, { path: "/login", element: _jsx(Login, {}) }), _jsx(Route, { path: "/forgot-password", element: _jsx(ForgotPassword, {}) }), _jsx(Route, { path: "/profile", element: _jsx(UserProfile, {}) }), _jsx(Route, { path: "/send-otp", element: _jsx(VerifyOTP, {}) }), _jsx(Route, { path: "/symptom-tracker", element: _jsx(SymptomTracker, {}) }), _jsx(Route, { path: "/discussion-forum", element: _jsx(DiscussionForum, {}) }), _jsx(Route, { path: "/discussion-forum/:id", element: _jsx(Discussion_details, {}) }), _jsx(Route, { path: "/info_hub", element: _jsx(InformationHub, {}) }), _jsx(Route, { path: "/marketplace", element: _jsx(Marketplace, {}) }), _jsx(Route, { path: "/marketplace/:id", element: _jsx(MarketplaceDetails, {}) }), _jsx(Route, { path: "/info_hub/news/:id", element: _jsx(NewsDetails, {}) }), _jsx(Route, { path: "/ikomek_assistant", element: _jsx(IkomekAssistant, {}) }), _jsx(Route, { path: "/info_hub/specialist/:id", element: _jsx(SpecialistDetails, {}) }), _jsx(Route, { path: "/info_hub/therapy-center/:id", element: _jsx(TherapyCenterDetails, {}) }), _jsx(Route, { path: "/menu", element: _jsx(Menu, {}) })] }) }));
};
export default App;
//# sourceMappingURL=App.js.map