import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import './styles.scss';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import Register from './auth/register/register/register';
import Login from './auth/login/login';
import ForgotPassword from './auth/forget_password/forget_password';
import SymptomTracker from './main_panel/symptom_tracker/symptom_tracker';
import UserProfile from './main_panel/profile/profile';
import VerifyOTP from './auth/register/otp/sendOTP';
import InformationHub from './main_panel/info_hub/information_hub';
import DiscussionForum from './main_panel/discussion_forum/discussion_forum/discussion_forum';
import Discussion_details from './main_panel/discussion_forum/discussion_forum_details/discussion_details';
import NewsDetails from './main_panel/info_hub/news_details';
import SpecialistDetails from './main_panel/info_hub/specialist_details';
import TherapyCenterDetails from './main_panel/info_hub/therapy_centers_details';
import Marketplace from './main_panel/marketplace/marketplace';
import MarketplaceDetails from './main_panel/marketplace/marketplace_details';
import IkomekAssistant from './main_panel/ikomek_ai_assistant/ikomek_assistant';
import Main_Page from './main_page/main_content/main_page';
import GlobalFonts from './styles/globalFonts';
import { Contact, PrivacyPolicy, Services, Support, About, } from './main_page/main_content/footer/footer_links/links';
const App = () => {
    return (_jsxs(Router, { children: [_jsx(GlobalFonts, {}), _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(Main_Page, {}) }), _jsx(Route, { path: "/about-us", element: _jsx(About, {}) }), _jsx(Route, { path: "/services", element: _jsx(Services, {}) }), _jsx(Route, { path: "/support", element: _jsx(Support, {}) }), _jsx(Route, { path: "/privacy-policy", element: _jsx(PrivacyPolicy, {}) }), _jsx(Route, { path: "/contact-us", element: _jsx(Contact, {}) }), _jsx(Route, { path: "/register", element: _jsx(Register, {}) }), _jsx(Route, { path: "/login", element: _jsx(Login, {}) }), _jsx(Route, { path: "/forgot-password", element: _jsx(ForgotPassword, {}) }), _jsx(Route, { path: "/profile", element: _jsx(UserProfile, {}) }), _jsx(Route, { path: "/send-otp", element: _jsx(VerifyOTP, {}) }), _jsx(Route, { path: "/symptom-tracker", element: _jsx(SymptomTracker, {}) }), _jsx(Route, { path: "/discussion-forum", element: _jsx(DiscussionForum, {}) }), _jsx(Route, { path: "/discussion-forum/:id", element: _jsx(Discussion_details, {}) }), _jsx(Route, { path: "/info_hub", element: _jsx(InformationHub, {}) }), _jsx(Route, { path: "/marketplace", element: _jsx(Marketplace, {}) }), _jsx(Route, { path: "/marketplace/public-items/:id", element: _jsx(MarketplaceDetails, {}) }), _jsx(Route, { path: "/marketplace/my-items/:id", element: _jsx(MarketplaceDetails, {}) }), _jsx(Route, { path: "/info_hub/news/:id", element: _jsx(NewsDetails, {}) }), _jsx(Route, { path: "/ikomek_assistant", element: _jsx(IkomekAssistant, {}) }), _jsx(Route, { path: "/info_hub/specialist/:id", element: _jsx(SpecialistDetails, {}) }), _jsx(Route, { path: "/info_hub/therapy-center/:id", element: _jsx(TherapyCenterDetails, {}) })] })] }));
};
export default App;
